title = "Sqitch"
baseURL = "https://sqitch.org/"
languageCode = "en-us"
disableKinds = ["term", "taxonomy", "RSS", "sitemap"]
copyright = "© Sqtich Hackers. This work is licensed under a Creative Commons Attribution 4.0 International License."
footnoteReturnLinkContents = "↩"
enableRobotsTXT = true

[params]
  description = "Sqitch is the developer-friendly, confidence-inducing, platform-neutral database change management system."

[markup]
  [markup.highlight]
    style = "monokai"
    codeFences = true
  [markup.goldmark.parser]
    autoHeadingID = true
  [markup.goldmark.renderer]
    unsafe = true
